apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - controller
  - rbac/controller-role.yaml
  - rbac/gitlab-runner-workflow-submitter.yaml

labels:
  - includeSelectors: true
    pairs:
      satellite.io/phase: phase3-pilot
