apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  config: |
    containerRuntimeExecutor: emissary
    executor:
      image: 192.168.10.238/library/argoexec:3.5.12-amd64-r1
    workflowNamespaces:
      - gitlab-runner
